# Generated by Django 4.2.4 on 2023-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
