# Generated by Django 4.2.4 on 2023-08-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0002_coupon_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon_code',
            options={'verbose_name_plural': 'Coupon Code'},
        ),
    ]
