# Generated by Django 4.2.4 on 2023-08-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrderId',
            new_name='orderId',
        ),
    ]
